"""add Role

Revision ID: a8ed9c148ebc
Revises: 3e55f2255f2b
Create Date: 2024-11-19 12:24:26.357449

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a8ed9c148ebc"
down_revision: Union[str, None] = "3e55f2255f2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE role as ENUM('admin', 'moderator', 'user')")
    op.add_column(
        "users",
        sa.Column("role", sa.Enum("admin", "moderator", "user", name="role"), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    op.execute("DROP TYPE role")
    # ### end Alembic commands ###
